name: vllm-project
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=11.8
  - numpy
  - pillow
  - matplotlib
  - pip
  - pip:
    - transformers>=4.30.0
    - datasets>=2.12.0
    - accelerate>=0.20.0
    - bitsandbytes>=0.40.0
    - peft>=0.4.0
    - trl>=0.5.0
    - "unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git"
    - tqdm>=4.60.0
